application:
  path_to_log_file: /home/pasha/sandbox/genshop/log.txt
  validate_schema_on_start: true
  logging_level: INFO

database:
  host : localhost
  user : genshopuser
  passwd : GenShop_123
  database : demodb

ameritrade:
  max_dataset_in_days: 1825 # 5 years
  client_id: GD7ONKYFFSYGOKAXFEFRKZDM3LRPAYXM

portfolio:
  instruments : [CSCO, KO, QCOM]